/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpnRouteImport } from './routes/upn'
import { Route as SplitsRouteImport } from './routes/splits'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as BillsRouteImport } from './routes/bills'
import { Route as IndexRouteImport } from './routes/index'

const UpnRoute = UpnRouteImport.update({
  id: '/upn',
  path: '/upn',
  getParentRoute: () => rootRouteImport,
} as any)
const SplitsRoute = SplitsRouteImport.update({
  id: '/splits',
  path: '/splits',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsRoute = BillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bills': typeof BillsRoute
  '/settings': typeof SettingsRoute
  '/splits': typeof SplitsRoute
  '/upn': typeof UpnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bills': typeof BillsRoute
  '/settings': typeof SettingsRoute
  '/splits': typeof SplitsRoute
  '/upn': typeof UpnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bills': typeof BillsRoute
  '/settings': typeof SettingsRoute
  '/splits': typeof SplitsRoute
  '/upn': typeof UpnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bills' | '/settings' | '/splits' | '/upn'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bills' | '/settings' | '/splits' | '/upn'
  id: '__root__' | '/' | '/bills' | '/settings' | '/splits' | '/upn'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillsRoute: typeof BillsRoute
  SettingsRoute: typeof SettingsRoute
  SplitsRoute: typeof SplitsRoute
  UpnRoute: typeof UpnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upn': {
      id: '/upn'
      path: '/upn'
      fullPath: '/upn'
      preLoaderRoute: typeof UpnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splits': {
      id: '/splits'
      path: '/splits'
      fullPath: '/splits'
      preLoaderRoute: typeof SplitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills': {
      id: '/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof BillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillsRoute: BillsRoute,
  SettingsRoute: SettingsRoute,
  SplitsRoute: SplitsRoute,
  UpnRoute: UpnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
